# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4887695a3d61b6229fb1318499abb89e8a2ec84d076a75d9983ba6fc8935dd24aaaeb994c395a1386e425e52628532e4f1d61c955c59bda0e65e70531a061ef1

test:
  secret_key_base: afaec7f5aadbacb3d6036f7b8f656e277e4d1e6c114222ccd71b9a4785498f244d4c3334732996d3a0b104a9348aa9105029af083b9e275836892e277d30396d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
